version: "3.8"

services:
  db:
    image: mysql
    container_name: gotea_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: senha123
      MYSQL_DATABASE: gotea_db
    volumes:
      - ../.docker/data:/var/lib/mysql
    ports:
      - "3306:3306"